version: "3"

networks:
  drone-net:

services:
  drone:
    container_name: drone
    image: drone/drone:2.13
    env_file:
      - drone.env
    volumes:
      - /var/lib/drone:/data
    ports:
      - 8088:80
    restart: always
    networks:
      - drone-net

  runner:
    container_name: runner
    image: drone/drone-runner-docker:latest
    depends_on:
      - drone
    env_file:
      - runner.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - drone-net


  drone-convert-paths-changed:
    container_name: dcpc
    image: meltwater/drone-convert-pathschanged
    depends_on:
      - drone
    env_file:
      - dcpc.env
    restart: always
    networks:
      - drone-net
    ports:
      - 3000:3000

